build:
  version: "2.0"

accounts:
  message: "Welcome to  accounts related prod APIs "
  contactDetails:
    name: "Syed - Product Owner"
    email: "s.siddik2709@gmail.com"
  onCallSupport:
    - 8522002553